// scope: poc
// Bundles the POC server into build/apps-script/: one Code.js (every file, in load order) plus
// appsscript.json. One file means Apps Script can't load them in the wrong order.
// Usage: node poc/scripts/build.mjs   then   npx @google/clasp push
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { sourceFiles } from "./source-order.mjs";

const HEADER = "// scope: poc\n// Generated by poc/scripts/build.mjs. Do not edit; change the source files instead.\n\n";

function toPosix(p) {
  return p.split("\\").join("/");
}

export function build({ root, outDir }) {
  const files = sourceFiles(root).map((file) => toPosix(relative(root, file)));
  const parts = files.map((file) => `// ---- ${file} ----\n${readFileSync(join(root, file), "utf8").trimEnd()}\n`);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "Code.js"), HEADER + parts.join("\n"));
  copyFileSync(join(root, "poc", "apps-script", "appsscript.json"), join(outDir, "appsscript.json"));
  return { outDir, files };
}

const isMain = Boolean(process.argv[1]) && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const root = fileURLToPath(new URL("../..", import.meta.url));
  const { outDir, files } = build({ root, outDir: join(root, "build", "apps-script") });
  console.log(`Wrote ${files.length} source files into ${toPosix(relative(root, outDir))}/Code.js`);
}
